### ISSUE TITLE
Fix tic-map-pipeline-script error with reduce func when the sequence is empty

### ISSUE THREAD

**Issue by luthfib** [RENCI/ctmd#427]
Get the following error when using the synthetic dataset:

```
INFO: processing table reviewer_organization extending columns WrappedArray()
ctmd-pipeline-dev | Exception in thread "main" java.lang.UnsupportedOperationException: empty.reduceLeft
ctmd-pipeline-dev |     at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
ctmd-pipeline-dev |     at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$reduceLeft(ArrayBuffer.scala:48)
ctmd-pipeline-dev |     at scala.collection.IndexedSeqOptimized$class.reduceLeft(IndexedSeqOptimized.scala:74)
ctmd-pipeline-dev |     at scala.collection.mutable.ArrayBuffer.reduceLeft(ArrayBuffer.scala:48)
ctmd-pipeline-dev |     at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
ctmd-pipeline-dev |     at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
ctmd-pipeline-dev |     at tic.Transform2$.main(Transform2.scala:545)
ctmd-pipeline-dev |     at tic.Transform2.main(Transform2.scala)
ctmd-pipeline-dev |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ctmd-pipeline-dev |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ctmd-pipeline-dev |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ctmd-pipeline-dev |     at java.lang.reflect.Method.invoke(Method.java:498)
ctmd-pipeline-dev |     at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
ctmd-pipeline-dev |     at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
ctmd-pipeline-dev | 2021-04-21 20:19:22;ERROR;pipeline encountered an error: 1
```

**Comment by xu-hao** [comment]
fix merged: https://github.com/RENCI/map-pipeline/commit/e6fc83d5ad797e9ec55f4213885e4c85becc07e2. @rajshruti18  do you know how the error was generated?

**Comment by rajshruti18** [comment]
> fix merged: [RENCI/map-pipeline@e6fc83d](https://github.com/RENCI/map-pipeline/commit/e6fc83d5ad797e9ec55f4213885e4c85becc07e2). @rajshruti18 do you know how the error was generated?

I do not know.

**Comment by dcarsey** [comment]
From 7-8-2021 internal meeting:  
(Hao) hasn’t been able to re-run Luthfi’s test - not in the tix how he got the error message
test data - he tried to ingest synthetic data set that Shruti created, and that is when the error came in
json file in ctmd synthetic data set repo to be checked by Hao
